# Generated by Django 4.2.30 on 2026-07-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('amended', 'Amended'), ('checked_in', 'Checked In')], default='active', max_length=20),
        ),
    ]
